steps:
  - name: ":bomb: Test"
    command: make test
    plugins:
      docker-compose#v4.16.0:
        run: terminal

  - wait
  - name: ":neckbeard: Benchmark"
    command: make bench
    plugins:
      docker-compose#v4.16.0:
        run: terminal

  - wait
  - name: ":hammer: Build"
    command: make dist
    artifact_paths: "dist/**.{gz,zip}"
    plugins:
      docker-compose#v4.16.0:
        run: terminal

  #- block: ":rocket: Release"

  #- name: ":octocat:"
  #  command: .buildkite/steps/release
  #  branches: "main"
  #  agents:
  #    queue: "deploy"

  #- name: ":packagecloud:"
  #  command: .buildkite/steps/package_and_upload
  #  branches: "main"
  #  agents:
  #    queue: "deploy"
